version: '3.1'
services:
  mysql_dev:
    restart: always
    image: mysql:5.7.30
    container_name: mysql_dev
    ports:
      - 3306:3306
    environment:
           #      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      #      --explicit_defaults_for_timestamp=true
      # --lower_case_table_names=1
      #     --max_allowed_packet=128M
      #  --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /usr/local/docker/mysql/data/:/var/lib/mysql
        #      - /usr/local/docker/mysql/conf/my.cnf:/etc/my.cnf:ro

  mysql_rel:
    restart: always
    image: mysql:5.7.30
    container_name: mysql_rel
    ports:
      - 4306:3306
    environment:
           #      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      #      --explicit_defaults_for_timestamp=true
      # --lower_case_table_names=1
      #     --max_allowed_packet=128M
      #  --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /usr/local/docker/mysql_rel:/var/lib/mysql

