version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    container_name: zookeeper
    networks: kafka212net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
    container_name: kafka
    networks: kafka212net

  kafka_manage:
    image: kafkamanager/kafka-manager:3.0.0.4
    container_name: kafka-manage-3004
    depends_on:
      - zookeeper
      - kafka
    ports:
    - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    networks:
    - kafka212net
  

networks:
  default:
    external:
      name: kafka212net